version: '2'
services:
  cbrain-portal:
    image: mcin/cbrain_portal:dev
    volumes:
     - ./volumes/portal/data_cache:/home/cbrain/cbrain_data_cache
     - ./volumes/portal/.ssh:/home/cbrain/.ssh
     - ./volumes/portal/plugins:/home/cbrain/plugins
    ports:
     - "${PORT}:3000"
    depends_on:
     - mysql
     - cbrain-bourreau
    environment:
      MODE: ${MODE}
      USERID: ${USERID}
      GROUPID: ${GROUPID}
      MYSQL_HOST: "mysql"
      MYSQL_USER: "cbrain_test"
      MYSQL_DATABASE: "cbrain"
      MYSQL_PASSWORD: "cbrain4567"
  mysql:
    image: mariadb:10.0
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_USER: "cbrain_test"
      MYSQL_DATABASE: "cbrain"
      MYSQL_PASSWORD: "cbrain4567"
  cbrain-bourreau:
    image: mcin/cbrain_bourreau:dev
    volumes:
     - ./volumes/portal/.ssh:/home/cbrain/.portal_ssh
     - ./volumes/bourreau/.ssh:/home/cbrain/.ssh
     - ./volumes/bourreau/data_cache:/home/cbrain/cbrain_data_cache
     - ./volumes/bourreau/plugins:/home/cbrain/plugins
     - ./volumes/bourreau/cbrain_task_directories:/home/cbrain/cbrain_task_directories
    environment:
      USERID: ${USERID}
      GROUPID: ${GROUPID}
      PORTAL_PORT: ${PORT}
      PORTAL_HOST: cbrain-portal
  data-provider:
    image: mcin/cbrain_data_provider:dev
    volumes:
     - ./volumes/portal/.ssh:/home/cbrain/.portal_ssh
     - ./volumes/data_provider/data:/home/cbrain/data
    environment:
      USERID: ${USERID}
      GROUPID: ${GROUPID}
      PORTAL_PORT: ${PORT}
      PORTAL_HOST: cbrain-portal
