version: '2'
services:
  cbrain-portal:
    image: mcin/cbrain_portal:dev
    volumes:
     - ./volumes/portal_data_cache:/home/cbrain/cbrain_data_cache
     - ./volumes/.ssh:/home/cbrain/.ssh
     - ./volumes/.bourreau_ssh:/home/cbrain/.bourreau_ssh
     - ./volumes/portal_plugins:/home/cbrain/plugins
     - ./volumes/data_provider:/home/cbrain/data_provider
    ports:
     - "${PORT}:3000"
    depends_on:
     - mysql
     - cbrain-bourreau
    environment:
      MODE: ${MODE}
      USERID: ${USERID}
      GROUPID: ${GROUPID}
      MYSQL_USER: "cbrain_test"
      MYSQL_DATABASE: "cbrain"
      MYSQL_PASSWORD: "cbrain4567"
  mysql:
    image: mariadb:10.0
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_USER: "cbrain_test"
      MYSQL_DATABASE: "cbrain"
      MYSQL_PASSWORD: "cbrain4567"
  cbrain-bourreau:
    image: mcin/cbrain_bourreau:dev
    volumes:
     - ./volumes/.bourreau_ssh:/home/cbrain/.ssh
     - ./volumes/portal_data_cache:/home/cbrain/cbrain_data_cache
     - ./volumes/bourreau_plugins:/home/cbrain/plugins
     - ./volumes/cbrain_task_directories:/home/cbrain/cbrain_task_directories
    ports:
     - "${SSH_PORT}:22"
    environment:
      USERID: ${USERID}
      GROUPID: ${GROUPID}
